# Generated by Django 6.0.3 on 2026-03-26 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_alter_transaction_amount_alter_transaction_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='notes',
            field=models.CharField(blank=True, max_length=500, verbose_name='Observação'),
        ),
    ]
