# Generated by Django 6.0.3 on 2026-03-27 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_transaction_accounts(apps, schema_editor):
    del schema_editor
    Transaction = apps.get_model("transactions", "Transaction")
    FinancialAccount = apps.get_model("transactions", "FinancialAccount")

    user_ids = Transaction.objects.order_by().values_list("user_id", flat=True).distinct()

    for user_id in user_ids:
        account, _ = FinancialAccount.objects.get_or_create(
            user_id=user_id,
            name="Conta principal",
            defaults={"is_active": True},
        )
        Transaction.objects.filter(user_id=user_id, account__isnull=True).update(account_id=account.id)


class Migration(migrations.Migration):
    dependencies = [
        ("categories", "0002_alter_category_created_at_alter_category_kind_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("transactions", "0003_transaction_notes"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentFile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Criado em")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Atualizado em")),
                (
                    "purpose",
                    models.CharField(
                        choices=[("import_source", "Arquivo de importação"), ("export_result", "Arquivo de exportação")],
                        max_length=30,
                        verbose_name="Finalidade",
                    ),
                ),
                ("original_name", models.CharField(max_length=255, verbose_name="Nome original")),
                ("content_type", models.CharField(blank=True, max_length=120, verbose_name="Tipo de conteúdo")),
                ("size_bytes", models.PositiveBigIntegerField(default=0, verbose_name="Tamanho (bytes)")),
                ("file", models.FileField(blank=True, upload_to="transactions/files/%Y/%m/%d", verbose_name="Arquivo")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_files",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FinancialAccount",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Criado em")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Atualizado em")),
                ("name", models.CharField(max_length=120, verbose_name="Nome")),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativa")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="financial_accounts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ExportJob",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Criado em")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Atualizado em")),
                (
                    "status",
                    models.CharField(
                        choices=[("queued", "Na fila"), ("processing", "Processando"), ("completed", "Concluído"), ("failed", "Falhou")],
                        default="queued",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "export_format",
                    models.CharField(choices=[("csv", "CSV"), ("xlsx", "XLSX")], max_length=10, verbose_name="Formato"),
                ),
                ("filters", models.JSONField(blank=True, default=dict, verbose_name="Filtros")),
                ("row_count", models.PositiveIntegerField(default=0, verbose_name="Quantidade de linhas")),
                ("error_message", models.TextField(blank=True, verbose_name="Erro")),
                (
                    "output_file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="export_jobs",
                        to="transactions.documentfile",
                        verbose_name="Arquivo gerado",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="export_jobs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ImportJob",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Criado em")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Atualizado em")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Rascunho"),
                            ("queued", "Na fila"),
                            ("processing", "Processando"),
                            ("completed", "Concluído"),
                            ("failed", "Falhou"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                ("column_mapping", models.JSONField(blank=True, default=dict, verbose_name="Mapeamento de colunas")),
                ("preview_summary", models.JSONField(blank=True, default=dict, verbose_name="Resumo do preview")),
                ("preview_rows", models.JSONField(blank=True, default=list, verbose_name="Linhas do preview")),
                ("imported_rows", models.PositiveIntegerField(default=0, verbose_name="Linhas importadas")),
                ("skipped_rows", models.PositiveIntegerField(default=0, verbose_name="Linhas puladas")),
                ("failed_rows", models.PositiveIntegerField(default=0, verbose_name="Linhas com falha")),
                ("error_message", models.TextField(blank=True, verbose_name="Erro")),
                (
                    "source_file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="import_jobs",
                        to="transactions.documentfile",
                        verbose_name="Arquivo de origem",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="import_jobs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ImportRowResult",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Criado em")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Atualizado em")),
                ("row_number", models.PositiveIntegerField(verbose_name="Número da linha")),
                (
                    "status",
                    models.CharField(
                        choices=[("imported", "Importado"), ("skipped", "Pulado"), ("failed", "Falhou")],
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                ("message", models.CharField(blank=True, max_length=255, verbose_name="Mensagem")),
                ("raw_data", models.JSONField(blank=True, default=dict, verbose_name="Dados brutos")),
                (
                    "import_job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rows",
                        to="transactions.importjob",
                        verbose_name="Lote de importação",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="transaction",
            name="import_id",
            field=models.CharField(blank=True, max_length=120, verbose_name="ID de importação"),
        ),
        migrations.AddField(
            model_name="transaction",
            name="payee",
            field=models.CharField(blank=True, max_length=255, verbose_name="Favorecido"),
        ),
        migrations.AddField(
            model_name="transaction",
            name="account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="transactions",
                to="transactions.financialaccount",
                verbose_name="Conta",
            ),
        ),
        migrations.RunPython(backfill_transaction_accounts, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="transaction",
            name="account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="transactions",
                to="transactions.financialaccount",
                verbose_name="Conta",
            ),
        ),
        migrations.AddField(
            model_name="importrowresult",
            name="transaction",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="import_rows",
                to="transactions.transaction",
                verbose_name="Transação",
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(fields=["user", "transaction_date", "amount", "payee"], name="transactions_tx_dedup_idx"),
        ),
        migrations.AddConstraint(
            model_name="financialaccount",
            constraint=models.UniqueConstraint(fields=("user", "name"), name="transactions_financial_account_user_name_unique"),
        ),
        migrations.AddConstraint(
            model_name="importrowresult",
            constraint=models.UniqueConstraint(fields=("import_job", "row_number"), name="transactions_import_row_result_job_row_unique"),
        ),
        migrations.AddConstraint(
            model_name="transaction",
            constraint=models.UniqueConstraint(
                condition=~models.Q(import_id=""),
                fields=("user", "import_id"),
                name="transactions_transaction_user_import_id_unique",
            ),
        ),
    ]
